FROM node
RUN mkdir -p /usr/src/node-red
RUN mkdir /data
WORKDIR /usr/src/node-red
RUN useradd --home-dir /usr/src/node-red --no-create-home node-red \
    && chown -R node-red:node-red /data \
    && chown -R node-red:node-red /usr/src/node-red \
    && usermod -a -G dialout node-red
USER node-red
ADD node-red/package.json /usr/src/node-red/
RUN npm install
RUN find node_modules/node-red-contrib-elasticsearch7 -type f -print | xargs perl -pi -e 's/_sourceInclude/_source_includes/g' 
EXPOSE 1880
ENV FLOWS=flows.json
ENV NODE_PATH=/usr/src/node-red/node_modules
CMD ["npm", "start", "--", "--userDir", "/data"]
